---
# Trabalho 1: Cálculo dos Elementos Orbitais
---

**Nome: Gregory Peruzzo Fiel**  

**Cartão: 00323639** 

---
* Data e horário para os cálculos celestes: **30/05/1999  19:00**
---

## Importação de módulos

In [93]:
#Seção de importação:
import math
import pandas as pd
import dash
from dash import dcc
import dash_html_components as html
import dash_table

## Cálculo do tempo

In [26]:
#Tempo
d =  30
m =  5
y =  1999
horas = 19
minutos = 0

t = math.floor(367 * y - math.floor((7 *(y + math.floor((m+9)/12)))/4) + 
               math.floor((275*m)/9) + d - 730530)
t += ((horas/24) + (minutos/1440))

print(f'O tempo é %.2f' %t)

O tempo é -214.21

## Funções utilizadas no trabalho

In [101]:
#Função para converter graus para radianos:
def deg2rad(theta):
  return(theta*math.pi/180)

#Função para converter radianos para graus:
def rad2deg(theta):
  return(theta*180/math.pi)

#Função para cálculo de anomalia excêntrica (E):
def calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e):
    delta_E = ((anomaliaMedia - anomaliaEAprox + e * math.sin(anomaliaEAprox)) /
               (1 - e * math.cos(anomaliaEAprox)))
    E = anomaliaEAprox + delta_E

    if abs(delta_E) > 5e-6:
        anomaliaEAprox = E
        delta_E = ((anomaliaMedia - anomaliaEAprox + e * math.sin(anomaliaEAprox)) /
                    (1 - e * math.cos(anomaliaEAprox)))
        E = anomaliaEAprox + delta_E
        print(f'E  : {round(E,3)}\n\u0394E : {delta_E}')
        return round(E, 3)
    else:
        print(f'E  : {round(E,3)}\n\u0394E : {delta_E}')
        return round(E, 3)

#Função para cálculo da anomalia verdadeira (v):
def calcularAnomaliaV(e, E):
    v = 2 * (math.atan((math.sqrt((1+e)/(1-e)))*math.tan(E/2)))
    print(f'v : {round(v,3)}')
    return round(v, 3)

#Função para cálculo da distância do planeta ao Sol:
def calcularR (alfa, e, v):
    au = 149597870700
    r = ((alfa * (1 - e**2)) / (1 + (e * math.cos(v))))
    print(f"A distância do Sol até o planeta: {round(r/au,3)} (au)")
    return r

#Função para cálculo das coordenadas cartesianas:
def calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i):
    km = 1000
    x = (r * (math.cos(longitudeNodo)*math.cos(argumentoPerielio + v) - math.sin(longitudeNodo)*math.sin(argumentoPerielio+v)*math.cos(i))) / km
    y = (r * (math.sin(longitudeNodo)*math.cos(argumentoPerielio + v) + math.cos(longitudeNodo)*math.sin(argumentoPerielio+v)*math.cos(i))) / km
    z = (r * math.sin(argumentoPerielio + v)*math.sin(i)) / km
    print(f'As coordenadas cartesianas do planeta: ({math.floor(x)},{math.floor(y)},{math.floor(z)}) em km')
    return x, y, z

#Função para cálculo das coordenadas eclípticas heliocêntricas:
def calcularCoordenadasEclip(x, y, z):
    lambda1 = math.atan(y/x) 
    beta1 = math.atan(z/(math.sqrt(x**2+y**2)))
    lambda1 = rad2deg(lambda1)
    beta1 = rad2deg(beta1)
    if lambda1 < 0:
        lambda1 += 360
        print(f'As coordenadas eclípticas heliocêntricas: ({round(lambda1,3)}, {round(beta1,3)}) graus')
        return lambda1, beta1
    else:
        print(f'As coordenadas eclípticas heliocêntricas: ({round(lambda1,3)}, {round(beta1,3)}) graus')
        return lambda1, beta1

#Função para adicionar os planetas dentro do DataFrame criado vazio:
coordenadasdf = pd.DataFrame(columns=['Planeta', 'X (km)', 'Y (km)', 'Z (km)', 'l (°)', 'b (°)'])
def adicionarPlaneta(coordenadasdf, planeta, x, y, z, l, b):
    novoRegistro = {'Planeta': planeta, 'X (km)': x, 'Y (km)': y, 'Z (km)': z, 'l (°)':l, 'b (°)':b}
    coordenadasdf = pd.concat([coordenadasdf, pd.DataFrame(novoRegistro, index=[0])], ignore_index=True)
    return coordenadasdf

## Cálculo dos elementos orbitais e coordenadas para cada planeta

### Mercúrio

In [102]:
#Mercúrio
longitudeNodo = 48.3313 + 3.24587e-5 * t
i = 7.0047 + 5.00e-8 * t
argumentoPerielio = 29.1241 + 1.01444e-5 * t
alfa = 0.387098 * 149597870700
e = 0.205635 + 5.59e-10 * t
anomaliaMedia = 168.6562 + 4.0923344368 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Mercúrio', x, y, z, l, b)
coordenadasdf

E  : -12.303
ΔE : -8.368029422553505e-05
v : 0.324
A distância do Sol até o planeta: 0.31 (au)
As coordenadas cartesianas do planeta: (-23401387,28437562,-28245859) em km
As coordenadas eclípticas heliocêntricas: (309.451, -37.487) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827

### Vênus

In [103]:
#Vênus
longitudeNodo = 76.6799 + 2.46590e-5 * t
i = 3.3946 + 2.75e-8 * t
argumentoPerielio = 54.8910 + 1.38374e-5 * t
alfa = 0.723330 * 149597870700
e = 0.006773 - 1.302e-9 * t
anomaliaMedia = 48.0052 + 1.6021302244 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Vênus', x, y, z, l, b)
coordenadasdf

E  : -5.146
ΔE : -1.162495062026709e-07
v : 1.143
A distância do Sol até o planeta: 0.721 (au)
As coordenadas cartesianas do planeta: (-22260468,104729989,13364528) em km
As coordenadas eclípticas heliocêntricas: (282.0, 7.115) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915

### Terra

In [104]:
#Terra
longitudeNodo = 0.0
i = 0.0
argumentoPerielio = 282.9404 + 4.70935e-5 * t
alfa = 1.000000 * 149597870700
e = 0.016709 - 1.151e-9 * t
anomaliaMedia = 356.0470 + 0.9856002585 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Terra', x, y, z, l, b)
coordenadasdf

E  : 2.539
ΔE : -4.2306765271779705e-07
v : 2.548
A distância do Sol até o planeta: 1.014 (au)
As coordenadas cartesianas do planeta: (-139291079,59981211,0) em km
As coordenadas eclípticas heliocêntricas: (336.702, 0.0) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915
2     Terra -1.392911e+08  5.998121e+07  0.000000e+00  336.702430   0.000000

### Marte

In [105]:
#Marte
longitudeNodo = 49.5574 + 2.11081e-5 * t
i = 1.8497 + 1.78e-8 * t
argumentoPerielio = 286.5016 + 2.92961e-5 * t
alfa = 1.523688 * 149597870700
e = 0.093405 + 2.516e-9 * t
anomaliaMedia = 18.6021 + 0.5240207766 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Marte', x, y, z, l, b)
coordenadasdf

E  : -1.727
ΔE : 0.00039341215047555844
v : -1.819
A distância do Sol até o planeta: 1.546 (au)
As coordenadas cartesianas do planeta: (-100924989,8525311,207898691) em km
As coordenadas eclípticas heliocêntricas: (355.172, 64.026) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915
2     Terra -1.392911e+08  5.998121e+07  0.000000e+00  336.702430   0.000000
3     Marte -1.009250e+08  8.525312e+06  2.078987e+08  355.171587  64.025507

### Júpiter

In [106]:
#Júpiter
longitudeNodo = 100.4542 + 2.76854e-5 * t
i = 1.3030 + 1.557e-8 * t
argumentoPerielio = 273.8777 + 1.64505e-5 * t
alfa = 5.20256 * 149597870700
e = 0.048498 + 4.469e-9 * t
anomaliaMedia = 19.8950 + 0.0830853001 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Júpiter', x, y, z, l, b)
coordenadasdf

E  : 0.038
ΔE : -3.30033524678665e-09
v : 0.04
A distância do Sol até o planeta: 4.95 (au)
As coordenadas cartesianas do planeta: (-620036197,-58924778,-400666308) em km
As coordenadas eclípticas heliocêntricas: (5.429, -32.753) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915
2     Terra -1.392911e+08  5.998121e+07  0.000000e+00  336.702430   0.000000
3     Marte -1.009250e+08  8.525312e+06  2.078987e+08  355.171587  64.025507
4   Júpiter -6.200362e+08 -5.892478e+07 -4.006663e+08    5.428767 -32.753168

### Saturno

In [107]:
#Saturno
longitudeNodo = 113.6634 + 2.38980e-5 * t
i = 2.4886 - 1.081e-7 * t
argumentoPerielio = 339.3939 + 2.97661e-5 * t
alfa = 9.55475 * 149597870700
e = 0.055546 - 9.499e-9 * t
anomaliaMedia = 316.9670 + 0.0334442282 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Saturno', x, y, z, l, b)
coordenadasdf

E  : 5.363
ΔE : 4.375494129441251e-05
v : -0.965
A distância do Sol até o planeta: 9.233 (au)
As coordenadas cartesianas do planeta: (308739293,1183863598,-641135348) em km
As coordenadas eclípticas heliocêntricas: (75.383, -27.656) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915
2     Terra -1.392911e+08  5.998121e+07  0.000000e+00  336.702430   0.000000
3     Marte -1.009250e+08  8.525312e+06  2.078987e+08  355.171587  64.025507
4   Júpiter -6.200362e+08 -5.892478e+07 -4.006663e+08    5.428767 -32.753168
5   Saturno  3.087393e+08  1.183864e+09 -6.411353e+08   75.383417 -27.656104

### Urano

In [108]:
#Urano
longitudeNodo = 74.0005 + 1.3978e-5 * t
i = 0.7733 + 1.9e-8 * t
argumentoPerielio = 96.6612 + 3.0565e-5 * t
alfa = ((19.18171 - 1.55e-8 * t) * 149597870700)
e = 0.047318 + 7.45e-9 * t
anomaliaMedia = 142.5905 + 0.011725806 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Urano', x, y, z, l, b)
coordenadasdf

E  : 2.474
ΔE : -1.2420321350472e-05
v : 2.503
A distância do Sol até o planeta: 19.895 (au)
As coordenadas cartesianas do planeta: (-1959432869,-928994402,-2038455811) em km
As coordenadas eclípticas heliocêntricas: (25.366, -43.229) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915
2     Terra -1.392911e+08  5.998121e+07  0.000000e+00  336.702430   0.000000
3     Marte -1.009250e+08  8.525312e+06  2.078987e+08  355.171587  64.025507
4   Júpiter -6.200362e+08 -5.892478e+07 -4.006663e+08    5.428767 -32.753168
5   Saturno  3.087393e+08  1.183864e+09 -6.411353e+08   75.383417 -27.656104
6     Urano -1.959433e+09 -9.289944e+08 -2.038456e+09   25.366281 -43.229406

### Netuno

In [109]:
#Netuno
longitudeNodo = 131.7806 + 3.0173e-5 * t
i = 1.7700 - 2.55e-7 * t
argumentoPerielio = 272.8461 - 6.027e-6 * t
alfa = ((30.05826 - 3.313e-8 * t) * 149597870700)
e = 0.008606 + 2.15e-9 * t
anomaliaMedia = 260.2471 + 0.005995147 * t
anomaliaMedia = deg2rad(anomaliaMedia)
anomaliaEAprox = anomaliaMedia
E = calcularAnomaliaE(anomaliaMedia, anomaliaEAprox, e)
v = calcularAnomaliaV(e, E)
r = calcularR(alfa, e, v)
x, y, z = calcularCoordenadasCart(r, longitudeNodo, argumentoPerielio, v, i)
l, b = calcularCoordenadasEclip(x, y, z)
coordenadasdf = adicionarPlaneta(coordenadasdf, 'Netuno', x, y, z, l, b)
coordenadasdf

E  : 4.511
ΔE : 2.9961489637527836e-07
v : -1.781
A distância do Sol até o planeta: 30.11 (au)
As coordenadas cartesianas do planeta: (2675874787,-1169911708,3429386525) em km
As coordenadas eclípticas heliocêntricas: (336.385, 49.582) graus

    Planeta        X (km)        Y (km)        Z (km)       l (°)      b (°)
0  Mercúrio -2.340139e+07  2.843756e+07 -2.824586e+07  309.451103 -37.486827
1     Vênus -2.226047e+07  1.047300e+08  1.336453e+07  281.999697   7.114915
2     Terra -1.392911e+08  5.998121e+07  0.000000e+00  336.702430   0.000000
3     Marte -1.009250e+08  8.525312e+06  2.078987e+08  355.171587  64.025507
4   Júpiter -6.200362e+08 -5.892478e+07 -4.006663e+08    5.428767 -32.753168
5   Saturno  3.087393e+08  1.183864e+09 -6.411353e+08   75.383417 -27.656104
6     Urano -1.959433e+09 -9.289944e+08 -2.038456e+09   25.366281 -43.229406
7    Netuno  2.675875e+09 -1.169912e+09  3.429387e+09  336.384705  49.582483

In [89]:
#Criação da tabela de massas para utilizar no cálculo do baricentro:
data = [
    {'Objeto': 'Sol', 'Massa (kg)': 1.9885e30},
    {'Objeto': 'Mercúrio', 'Massa (kg)': 3.3011e23},
    {'Objeto': 'Vênus', 'Massa (kg)': 4.8675e24},
    {'Objeto': 'Terra', 'Massa (kg)': 5.9722e24},
    {'Objeto': 'Marte', 'Massa (kg)': 6.4171e23},
    {'Objeto': 'Júpiter', 'Massa (kg)': 1.8981e27},
    {'Objeto': 'Saturno', 'Massa (kg)': 5.6834e26},
    {'Objeto': 'Urano', 'Massa (kg)': 8.6810e25},
    {'Objeto': 'Netuno', 'Massa (kg)': 1.0241e26}
]
massasdf = pd.DataFrame(data)
massasdf

     Objeto    Massa (kg)
0       Sol  1.988500e+30
1  Mercúrio  3.301100e+23
2     Vênus  4.867500e+24
3     Terra  5.972200e+24
4     Marte  6.417100e+23
5   Júpiter  1.898100e+27
6   Saturno  5.683400e+26
7     Urano  8.681000e+25
8    Netuno  1.024100e+26